# Generated by Django 6.1.1 on 2026-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
