# Generated by Django 6.1.1 on 2026-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsource_jobingestionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='min_years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
