# Generated by Django 6.1.1 on 2026-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0002_careerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='career_profiles', to='skills.skill'),
        ),
    ]
