# Generated by Django 6.1.1 on 2026-09-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_careerprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_job_titles', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('preferred_work_types', models.JSONField(blank=True, default=list)),
                ('min_years_of_experience', models.PositiveIntegerField(default=0)),
                ('max_years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.careerprofile')),
            ],
            options={
                'verbose_name': 'Career Preferences',
                'verbose_name_plural': 'Career Preferences',
            },
        ),
    ]
