# Generated by Django 6.1.1 on 2026-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
